server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://project-service
          predicates:
            - Path=/project/**
        - id: customer-service
          uri: lb://projectTask-service
          predicates:
            - Path=/task/**
        - id: shopping-service
          uri: lb://backlog-service
          predicates:
            - Path=/backlog/**
