server:
  port: 9011
spring:
  application:
    name: projectTask-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:projecttaskDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  boot:
    admin:
      client:
        url: http://localhost:9020
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
